# Sharechain links used by cloud content/update fetchers.
title_compendium.url=http://sharechain.qq.com/dd62be90d8b4db9a64ff91f3d30f7f73?qq_aio_chat_type=2
donation_leaderboard.url=http://sharechain.qq.com/ad02296d23d23f928b07f3a83677d166
update_primary.url=http://sharechain.qq.com/e212f77e7f2b144573436443a08175fc
update_changelog.url=http://sharechain.qq.com/eba665b08b447f76c5a267af0fceeeea
hall_of_fame.url=http://sharechain.qq.com/1f4c761975ee8fdd9dd41dbf5a14f342
enhancement_attr.url=http://sharechain.qq.com/b8ee71b964be07aab508781044692cf6?qq_aio_chat_type=2
ad_exp_list.url=http://sharechain.qq.com/6c7db7992da41afa68e90751d3c4b4e0?qq_aio_chat_type=2
